services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel/app
        container_name: app
        environment:
            AUTORUN_ENABLED: true
            APP_BASE_DIR: /var/www
            NGINX_WEBROOT: /var/www/public
            PHP_MEMORY_LIMIT: 128M
            PHP_OPCACHE_ENABLE: 1
            PHP_UPLOAD_MAX_FILE_SIZE: 10M
            PHP_POST_MAX_SIZE: 10M
            NGINX_UPLOAD_LIMIT: 10M
            NGINX_REQUEST_TIMEOUT: 30
            SSL_MODE: off
        volumes:
            - ./.env:/var/www/.env:ro
        networks:
            - traefik
        labels:
            - traefik.enable=true
            - traefik.http.routers.laravel.rule=Host(`localhost`)
            - traefik.http.routers.laravel.entrypoints=web
            - traefik.http.services.laravel-service.loadbalancer.server.port=8080

    queue:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel/app
        scale: 4
        environment:
            AUTORUN_ENABLED: true
            APP_BASE_DIR: /var/www
            PHP_MEMORY_LIMIT: 128M
            SHOW_WELCOME_MESSAGE: false
        command: ['php', '/var/www/artisan', 'queue:work', 'redis', '--tries=3', '--backoff=5']
        stop_signal: SIGTERM

networks:
    laravel:
    traefik:
        external: true
